Usage documentation in README
Wolox/pagination-node pull request #11
Opened 2020-04-08 00:20 UTC by juanpablo-rojas

2020-06-18 18:51 UTC, redwarewolf requested changes

2020-06-18 18:51 UTC, redwarewolf commented on README.md
> +The package allows you to transform a collection of objects into a paginated JSON response format with certain pagination parameters.
What about changing "The" to "This"?

2020-06-18 18:51 UTC, redwarewolf commented on README.md
> +The package is able to slice the entire collection sent based on the `limit` and the `page` parameters that can be specified to the `paginate` method of the package, and therefore return just the por
As to avoid repetition
"It's able to..."
"Pagination-Node slices the entire...."

2020-06-18 18:51 UTC, redwarewolf commented on README.md
> +* 'pagination params': These are the params that accompany the page itself (resulting objects), and are strictly related with the mentioned page that was requested. So far, the default pagination par
`pagination params` instead of 'pagination params'

2020-06-18 18:51 UTC, redwarewolf commented on README.md
> +If you wanted to stablish different option values as defaults all you have to do is set the needed value to the corresponding option like this:
What about "If you want to.."?

2020-06-18 18:51 UTC, redwarewolf commented on README.md
> +It's recommended to do this on a setup/startup step of the applicacion that requires the tool, for example requiring it and changing its default values in a script that runs before a controller rende
What about changing it to "...and changing It's default values in a middleware that runs before the controller action that utilizes this tool"

2020-06-19 14:49 UTC, mpuricawolox approved these changes

2020-06-19 14:50 UTC, redwarewolf approved these changes

2020-06-19 14:51 UTC, merged